In [1]:
import numpy as np;

#utwórz tablicę zawierającą 10 zer
zeros_array = np.zeros(10)
print("Zeros: \n", zeros_array, "\n")


Zeros: 
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 



In [2]:
#utwórz tablicę zawierającą 10 piątek
fives_array = np.ones(10)*5
print("Fives: \n", fives_array, "\n")


Fives: 
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.] 



In [3]:
#utwórz tablicę zawierającą liczby od 10 do 50
values = np.arange(10,51,1)
print("Values: \n", values, "\n")




Values: 
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50] 



In [4]:
#utwórz macierz o wymiarach 3x3 zawierającą liczby od 0 do 8
matrix = np.arange(0,9,1).reshape(3,3)
print("3x3 matrix: \n", matrix, "\n")




3x3 matrix: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]] 



In [5]:
#utwórz macierz jednostkową o wymiarach 3x3
identity_matrix = np.identity(3)
print("3x3 identity matrix: \n", identity_matrix, "\n")




3x3 identity matrix: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 



In [6]:
#utwórz macierz o wymiarach 5x5 zawierającą liczby z dystrybucji normalnej (Gaussa),
gauss_distribution = np.random.normal(size=(5,5))
print("Gauss distribution: \n", gauss_distribution, "\n")




Gauss distribution: 
 [[-2.25022    -0.59733872 -0.5029569   0.10091463  0.94910471]
 [ 0.51574657 -1.40861608 -1.18970882  1.65421321 -0.52995391]
 [ 1.37146184  0.36494576 -0.13542525 -1.83032585 -0.43315399]
 [-1.2524528   1.96017072 -0.26559272  1.25246443  0.0887702 ]
 [-0.50507066 -2.10132028 -0.13318085  0.61270502  0.38018544]] 



In [7]:
#utwórz macierz o wymiarach 10x10 zawierającą liczby od 0,01 do 1 z krokiem 0,01
matrix_small_step = np.arange(0.01,1.01,0.01).reshape(10,10)
print("From 0.01 to 1: \n", matrix_small_step, "\n")




From 0.01 to 1: 
 [[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]] 



In [8]:
#utwórz tablicę zawierającą 20 liniowo rozłożonych liczb między 0 a 1 (włącznie z 0 i 1)
linear_distribute = np.linspace(0,1,20)
print("Linear distribution: \n", linear_distribute, "\n")




Linear distribution: 
 [0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ] 



In [9]:
#utwórz tablicę zawierającą losowe liczby z przedziału (1, 25),
#następnie zamień ją na macierz o wymiarach 5 x 5 z tymi samymi liczbami
#oblicz sumę wszystkich liczb w ww. macierzy,
#oblicz średnią wszystkich liczb w ww. macierzy,
#oblicz standardową dewiację dla liczb w ww. macierzy,
#oblicz sumę każdej kolumny ww. macierzy i zapisz ją do tablicy.
random_numbers = np.random.randint(1, 26, 25)
print("Random numbers: \n", random_numbers, "\n")
random_numbers = random_numbers.reshape(5,5)
print("Random numbers but in matrix: \n", random_numbers, "\n")
print("Sum of numbers: \n", random_numbers.sum(), "\n")
print("Mean of numbers: \n", random_numbers.mean(), "\n")
print("Deviation of numbers: \n", random_numbers.std(), "\n") 
print("Sum of columns: \n", random_numbers.sum(axis=0), "\n")




Random numbers: 
 [18 22  1  1 14 14  1 15  1  5 12  3 10 15  5 21  6 21 22 24 24 18 24 20
 21] 

Random numbers but in matrix: 
 [[18 22  1  1 14]
 [14  1 15  1  5]
 [12  3 10 15  5]
 [21  6 21 22 24]
 [24 18 24 20 21]] 

Sum of numbers: 
 338 

Mean of numbers: 
 13.52 

Deviation of numbers: 
 8.203023832709498 

Sum of columns: 
 [89 50 71 59 69] 



In [10]:
#utwórz macierz o wymiarach 5x5 zawierającą losowe liczby z przedziału (0, 100) i:
#oblicz medianę tych liczb,
#znajdź najmniejszą liczbę tej macierzy,
#znajdź największą liczbę tej macierzy.
random_numbers_5x5 = np.random.randint(1, 101, (5, 5))
print(random_numbers_5x5)
print("Median of numbers: \n", np.median(random_numbers_5x5), "\n") 
print("Min value: \n", np.min(random_numbers_5x5), "\n") 
print("Max value: \n", np.max(random_numbers_5x5), "\n") 




[[ 94   8  24  90  13]
 [ 43  58   9  36  92]
 [ 34   4  28  52  51]
 [ 70  78  17  27 100]
 [ 62  63   3  22   4]]
Median of numbers: 
 36.0 

Min value: 
 3 

Max value: 
 100 



In [11]:
#utwórz macierz o wymiarach różnych od siebie i większych od 1, zawierającą losowe liczby z przedziału (0, 100) i dokonaj jej transpozycji,
diff_matrix = np.random.randint(0, 101,(3,2))
print("Diff matrix: \n", diff_matrix, "\n")
print("Transposition: \n", diff_matrix.transpose(), "\n")




Diff matrix: 
 [[52 33]
 [56  2]
 [90 54]] 

Transposition: 
 [[52 56 90]
 [33  2 54]] 



In [12]:
#utwórz dwie macierze o odpowiednich wymiarach (doczytać), większych od 2 i dodaj je do siebie,
matrix_M = np.random.randint(2, 11)
matrix_N = np.random.randint(2, 11)
matrix_A = np.random.randint(0, 100, (matrix_M, matrix_N))
print("Matrix A: \n", matrix_A, "\n")
matrix_B = np.random.randint(0, 100, (matrix_M, matrix_N))
print("Matrix B: \n", matrix_B, "\n")
print("Sum of matrixes: \n", matrix_A + matrix_B, "\n")




Matrix A: 
 [[12 18 11 14 86]
 [49 41 98 31 15]
 [28 96 11 19 66]
 [14 90  6 14 31]
 [28 71 46 82 14]
 [35 72 10 11 27]
 [73  2 71 86 78]
 [97 30 26 67 23]
 [97 91 31 59 29]] 

Matrix B: 
 [[87 28 94 94 47]
 [44 70 49  1 12]
 [50 22 22 33 17]
 [38 25 78 75 39]
 [12 23 41 35  8]
 [86 32 61  7 74]
 [86  2 99 69 35]
 [44 99 62  5 73]
 [45 96 58  0 87]] 

Sum of matrixes: 
 [[ 99  46 105 108 133]
 [ 93 111 147  32  27]
 [ 78 118  33  52  83]
 [ 52 115  84  89  70]
 [ 40  94  87 117  22]
 [121 104  71  18 101]
 [159   4 170 155 113]
 [141 129  88  72  96]
 [142 187  89  59 116]] 



In [13]:
#utwórz dwie macierze o odpowiednich wymiarach (doczytać) różnych od siebie i większych od 2,
#a następnie pomnóż je przez siebie za pomocą dwóch różnych funkcji (np. ‘matmul’ i ‘multiply’)
#Warunek mnożenia macierzy: Matrix_A[M x N] * Matrix_B[N x P] = Matrix_C[M x P]
matrix_M_multiply = np.random.randint(2, 5)
matrix_N_multiply = np.random.randint(2, 5)
matrix_A_multiply = np.random.randint(0, 100, (matrix_M_multiply, matrix_N_multiply)).transpose()
print("Matrix A: \n", matrix_A_multiply, "\n")
matrix_B_multiply = np.random.randint(0, 100, (matrix_M_multiply, matrix_N_multiply))
print("Matrix B: \n", matrix_B_multiply, "\n")
print("Matmul of matrixes: \n", np.matmul(matrix_A_multiply, matrix_B_multiply), "\n")

Matrix A: 
 [[46  7 34 97]
 [89 45 66 21]
 [64 48 51 79]] 

Matrix B: 
 [[25 86 84]
 [80 81  2]
 [11 23  1]
 [70  3 93]] 

Matmul of matrixes: 
 [[ 8874  5596 12933]
 [ 8021 12880  9585]
 [11531 10802 12870]] 

